/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CenterRouteImport } from './routes/center'
import { Route as BuiucaniRouteImport } from './routes/buiucani'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as StudioLangRouteImport } from './routes/$studio.$lang'
import { Route as LangSpecialistsRouteImport } from './routes/$lang.specialists'
import { Route as LangProductsRouteImport } from './routes/$lang.products'
import { Route as LangPricingRouteImport } from './routes/$lang.pricing'
import { Route as LangContactsRouteImport } from './routes/$lang.contacts'
import { Route as LangBookRouteImport } from './routes/$lang.book'
import { Route as LangSplatRouteImport } from './routes/$lang.$'
import { Route as StudioLangIndexRouteImport } from './routes/$studio.$lang.index'
import { Route as StudioLangSpecialistsRouteImport } from './routes/$studio.$lang.specialists'
import { Route as StudioLangProductsRouteImport } from './routes/$studio.$lang.products'
import { Route as StudioLangPricingRouteImport } from './routes/$studio.$lang.pricing'
import { Route as StudioLangContactsRouteImport } from './routes/$studio.$lang.contacts'
import { Route as StudioLangBookRouteImport } from './routes/$studio.$lang.book'
import { Route as StudioLangSplatRouteImport } from './routes/$studio.$lang.$'
import { Route as LangSpecialistsBookRouteImport } from './routes/$lang.specialists.book'
import { Route as LangProductsBookRouteImport } from './routes/$lang.products.book'
import { Route as LangPricingBookRouteImport } from './routes/$lang.pricing.book'
import { Route as LangContactsBookRouteImport } from './routes/$lang.contacts.book'
import { Route as StudioLangSpecialistsBookRouteImport } from './routes/$studio.$lang.specialists.book'
import { Route as StudioLangProductsBookRouteImport } from './routes/$studio.$lang.products.book'
import { Route as StudioLangPricingBookRouteImport } from './routes/$studio.$lang.pricing.book'
import { Route as StudioLangContactsBookRouteImport } from './routes/$studio.$lang.contacts.book'

const CenterRoute = CenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiucaniRoute = BuiucaniRouteImport.update({
  id: '/buiucani',
  path: '/buiucani',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const StudioLangRoute = StudioLangRouteImport.update({
  id: '/$studio/$lang',
  path: '/$studio/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSpecialistsRoute = LangSpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsRoute = LangProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LangRoute,
} as any)
const LangPricingRoute = LangPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LangRoute,
} as any)
const LangContactsRoute = LangContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LangRoute,
} as any)
const LangBookRoute = LangBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangRoute,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangRoute,
} as any)
const StudioLangIndexRoute = StudioLangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangSpecialistsRoute = StudioLangSpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangProductsRoute = StudioLangProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangPricingRoute = StudioLangPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangContactsRoute = StudioLangContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangBookRoute = StudioLangBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StudioLangRoute,
} as any)
const StudioLangSplatRoute = StudioLangSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudioLangRoute,
} as any)
const LangSpecialistsBookRoute = LangSpecialistsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangSpecialistsRoute,
} as any)
const LangProductsBookRoute = LangProductsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangProductsRoute,
} as any)
const LangPricingBookRoute = LangPricingBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangPricingRoute,
} as any)
const LangContactsBookRoute = LangContactsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangContactsRoute,
} as any)
const StudioLangSpecialistsBookRoute =
  StudioLangSpecialistsBookRouteImport.update({
    id: '/book',
    path: '/book',
    getParentRoute: () => StudioLangSpecialistsRoute,
  } as any)
const StudioLangProductsBookRoute = StudioLangProductsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StudioLangProductsRoute,
} as any)
const StudioLangPricingBookRoute = StudioLangPricingBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StudioLangPricingRoute,
} as any)
const StudioLangContactsBookRoute = StudioLangContactsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => StudioLangContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang': typeof LangRouteWithChildren
  '/buiucani': typeof BuiucaniRoute
  '/center': typeof CenterRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRouteWithChildren
  '/$lang/pricing': typeof LangPricingRouteWithChildren
  '/$lang/products': typeof LangProductsRouteWithChildren
  '/$lang/specialists': typeof LangSpecialistsRouteWithChildren
  '/$studio/$lang': typeof StudioLangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/contacts/book': typeof LangContactsBookRoute
  '/$lang/pricing/book': typeof LangPricingBookRoute
  '/$lang/products/book': typeof LangProductsBookRoute
  '/$lang/specialists/book': typeof LangSpecialistsBookRoute
  '/$studio/$lang/$': typeof StudioLangSplatRoute
  '/$studio/$lang/book': typeof StudioLangBookRoute
  '/$studio/$lang/contacts': typeof StudioLangContactsRouteWithChildren
  '/$studio/$lang/pricing': typeof StudioLangPricingRouteWithChildren
  '/$studio/$lang/products': typeof StudioLangProductsRouteWithChildren
  '/$studio/$lang/specialists': typeof StudioLangSpecialistsRouteWithChildren
  '/$studio/$lang/': typeof StudioLangIndexRoute
  '/$studio/$lang/contacts/book': typeof StudioLangContactsBookRoute
  '/$studio/$lang/pricing/book': typeof StudioLangPricingBookRoute
  '/$studio/$lang/products/book': typeof StudioLangProductsBookRoute
  '/$studio/$lang/specialists/book': typeof StudioLangSpecialistsBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/buiucani': typeof BuiucaniRoute
  '/center': typeof CenterRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRouteWithChildren
  '/$lang/pricing': typeof LangPricingRouteWithChildren
  '/$lang/products': typeof LangProductsRouteWithChildren
  '/$lang/specialists': typeof LangSpecialistsRouteWithChildren
  '/$lang': typeof LangIndexRoute
  '/$lang/contacts/book': typeof LangContactsBookRoute
  '/$lang/pricing/book': typeof LangPricingBookRoute
  '/$lang/products/book': typeof LangProductsBookRoute
  '/$lang/specialists/book': typeof LangSpecialistsBookRoute
  '/$studio/$lang/$': typeof StudioLangSplatRoute
  '/$studio/$lang/book': typeof StudioLangBookRoute
  '/$studio/$lang/contacts': typeof StudioLangContactsRouteWithChildren
  '/$studio/$lang/pricing': typeof StudioLangPricingRouteWithChildren
  '/$studio/$lang/products': typeof StudioLangProductsRouteWithChildren
  '/$studio/$lang/specialists': typeof StudioLangSpecialistsRouteWithChildren
  '/$studio/$lang': typeof StudioLangIndexRoute
  '/$studio/$lang/contacts/book': typeof StudioLangContactsBookRoute
  '/$studio/$lang/pricing/book': typeof StudioLangPricingBookRoute
  '/$studio/$lang/products/book': typeof StudioLangProductsBookRoute
  '/$studio/$lang/specialists/book': typeof StudioLangSpecialistsBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$lang': typeof LangRouteWithChildren
  '/buiucani': typeof BuiucaniRoute
  '/center': typeof CenterRoute
  '/$lang/$': typeof LangSplatRoute
  '/$lang/book': typeof LangBookRoute
  '/$lang/contacts': typeof LangContactsRouteWithChildren
  '/$lang/pricing': typeof LangPricingRouteWithChildren
  '/$lang/products': typeof LangProductsRouteWithChildren
  '/$lang/specialists': typeof LangSpecialistsRouteWithChildren
  '/$studio/$lang': typeof StudioLangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/contacts/book': typeof LangContactsBookRoute
  '/$lang/pricing/book': typeof LangPricingBookRoute
  '/$lang/products/book': typeof LangProductsBookRoute
  '/$lang/specialists/book': typeof LangSpecialistsBookRoute
  '/$studio/$lang/$': typeof StudioLangSplatRoute
  '/$studio/$lang/book': typeof StudioLangBookRoute
  '/$studio/$lang/contacts': typeof StudioLangContactsRouteWithChildren
  '/$studio/$lang/pricing': typeof StudioLangPricingRouteWithChildren
  '/$studio/$lang/products': typeof StudioLangProductsRouteWithChildren
  '/$studio/$lang/specialists': typeof StudioLangSpecialistsRouteWithChildren
  '/$studio/$lang/': typeof StudioLangIndexRoute
  '/$studio/$lang/contacts/book': typeof StudioLangContactsBookRoute
  '/$studio/$lang/pricing/book': typeof StudioLangPricingBookRoute
  '/$studio/$lang/products/book': typeof StudioLangProductsBookRoute
  '/$studio/$lang/specialists/book': typeof StudioLangSpecialistsBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$lang'
    | '/buiucani'
    | '/center'
    | '/$lang/$'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/pricing'
    | '/$lang/products'
    | '/$lang/specialists'
    | '/$studio/$lang'
    | '/$lang/'
    | '/$lang/contacts/book'
    | '/$lang/pricing/book'
    | '/$lang/products/book'
    | '/$lang/specialists/book'
    | '/$studio/$lang/$'
    | '/$studio/$lang/book'
    | '/$studio/$lang/contacts'
    | '/$studio/$lang/pricing'
    | '/$studio/$lang/products'
    | '/$studio/$lang/specialists'
    | '/$studio/$lang/'
    | '/$studio/$lang/contacts/book'
    | '/$studio/$lang/pricing/book'
    | '/$studio/$lang/products/book'
    | '/$studio/$lang/specialists/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/buiucani'
    | '/center'
    | '/$lang/$'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/pricing'
    | '/$lang/products'
    | '/$lang/specialists'
    | '/$lang'
    | '/$lang/contacts/book'
    | '/$lang/pricing/book'
    | '/$lang/products/book'
    | '/$lang/specialists/book'
    | '/$studio/$lang/$'
    | '/$studio/$lang/book'
    | '/$studio/$lang/contacts'
    | '/$studio/$lang/pricing'
    | '/$studio/$lang/products'
    | '/$studio/$lang/specialists'
    | '/$studio/$lang'
    | '/$studio/$lang/contacts/book'
    | '/$studio/$lang/pricing/book'
    | '/$studio/$lang/products/book'
    | '/$studio/$lang/specialists/book'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$lang'
    | '/buiucani'
    | '/center'
    | '/$lang/$'
    | '/$lang/book'
    | '/$lang/contacts'
    | '/$lang/pricing'
    | '/$lang/products'
    | '/$lang/specialists'
    | '/$studio/$lang'
    | '/$lang/'
    | '/$lang/contacts/book'
    | '/$lang/pricing/book'
    | '/$lang/products/book'
    | '/$lang/specialists/book'
    | '/$studio/$lang/$'
    | '/$studio/$lang/book'
    | '/$studio/$lang/contacts'
    | '/$studio/$lang/pricing'
    | '/$studio/$lang/products'
    | '/$studio/$lang/specialists'
    | '/$studio/$lang/'
    | '/$studio/$lang/contacts/book'
    | '/$studio/$lang/pricing/book'
    | '/$studio/$lang/products/book'
    | '/$studio/$lang/specialists/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LangRoute: typeof LangRouteWithChildren
  BuiucaniRoute: typeof BuiucaniRoute
  CenterRoute: typeof CenterRoute
  StudioLangRoute: typeof StudioLangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/center': {
      id: '/center'
      path: '/center'
      fullPath: '/center'
      preLoaderRoute: typeof CenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buiucani': {
      id: '/buiucani'
      path: '/buiucani'
      fullPath: '/buiucani'
      preLoaderRoute: typeof BuiucaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$studio/$lang': {
      id: '/$studio/$lang'
      path: '/$studio/$lang'
      fullPath: '/$studio/$lang'
      preLoaderRoute: typeof StudioLangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/specialists': {
      id: '/$lang/specialists'
      path: '/specialists'
      fullPath: '/$lang/specialists'
      preLoaderRoute: typeof LangSpecialistsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products': {
      id: '/$lang/products'
      path: '/products'
      fullPath: '/$lang/products'
      preLoaderRoute: typeof LangProductsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/pricing': {
      id: '/$lang/pricing'
      path: '/pricing'
      fullPath: '/$lang/pricing'
      preLoaderRoute: typeof LangPricingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contacts': {
      id: '/$lang/contacts'
      path: '/contacts'
      fullPath: '/$lang/contacts'
      preLoaderRoute: typeof LangContactsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/book': {
      id: '/$lang/book'
      path: '/book'
      fullPath: '/$lang/book'
      preLoaderRoute: typeof LangBookRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$studio/$lang/': {
      id: '/$studio/$lang/'
      path: '/'
      fullPath: '/$studio/$lang/'
      preLoaderRoute: typeof StudioLangIndexRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/specialists': {
      id: '/$studio/$lang/specialists'
      path: '/specialists'
      fullPath: '/$studio/$lang/specialists'
      preLoaderRoute: typeof StudioLangSpecialistsRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/products': {
      id: '/$studio/$lang/products'
      path: '/products'
      fullPath: '/$studio/$lang/products'
      preLoaderRoute: typeof StudioLangProductsRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/pricing': {
      id: '/$studio/$lang/pricing'
      path: '/pricing'
      fullPath: '/$studio/$lang/pricing'
      preLoaderRoute: typeof StudioLangPricingRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/contacts': {
      id: '/$studio/$lang/contacts'
      path: '/contacts'
      fullPath: '/$studio/$lang/contacts'
      preLoaderRoute: typeof StudioLangContactsRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/book': {
      id: '/$studio/$lang/book'
      path: '/book'
      fullPath: '/$studio/$lang/book'
      preLoaderRoute: typeof StudioLangBookRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$studio/$lang/$': {
      id: '/$studio/$lang/$'
      path: '/$'
      fullPath: '/$studio/$lang/$'
      preLoaderRoute: typeof StudioLangSplatRouteImport
      parentRoute: typeof StudioLangRoute
    }
    '/$lang/specialists/book': {
      id: '/$lang/specialists/book'
      path: '/book'
      fullPath: '/$lang/specialists/book'
      preLoaderRoute: typeof LangSpecialistsBookRouteImport
      parentRoute: typeof LangSpecialistsRoute
    }
    '/$lang/products/book': {
      id: '/$lang/products/book'
      path: '/book'
      fullPath: '/$lang/products/book'
      preLoaderRoute: typeof LangProductsBookRouteImport
      parentRoute: typeof LangProductsRoute
    }
    '/$lang/pricing/book': {
      id: '/$lang/pricing/book'
      path: '/book'
      fullPath: '/$lang/pricing/book'
      preLoaderRoute: typeof LangPricingBookRouteImport
      parentRoute: typeof LangPricingRoute
    }
    '/$lang/contacts/book': {
      id: '/$lang/contacts/book'
      path: '/book'
      fullPath: '/$lang/contacts/book'
      preLoaderRoute: typeof LangContactsBookRouteImport
      parentRoute: typeof LangContactsRoute
    }
    '/$studio/$lang/specialists/book': {
      id: '/$studio/$lang/specialists/book'
      path: '/book'
      fullPath: '/$studio/$lang/specialists/book'
      preLoaderRoute: typeof StudioLangSpecialistsBookRouteImport
      parentRoute: typeof StudioLangSpecialistsRoute
    }
    '/$studio/$lang/products/book': {
      id: '/$studio/$lang/products/book'
      path: '/book'
      fullPath: '/$studio/$lang/products/book'
      preLoaderRoute: typeof StudioLangProductsBookRouteImport
      parentRoute: typeof StudioLangProductsRoute
    }
    '/$studio/$lang/pricing/book': {
      id: '/$studio/$lang/pricing/book'
      path: '/book'
      fullPath: '/$studio/$lang/pricing/book'
      preLoaderRoute: typeof StudioLangPricingBookRouteImport
      parentRoute: typeof StudioLangPricingRoute
    }
    '/$studio/$lang/contacts/book': {
      id: '/$studio/$lang/contacts/book'
      path: '/book'
      fullPath: '/$studio/$lang/contacts/book'
      preLoaderRoute: typeof StudioLangContactsBookRouteImport
      parentRoute: typeof StudioLangContactsRoute
    }
  }
}

interface LangContactsRouteChildren {
  LangContactsBookRoute: typeof LangContactsBookRoute
}

const LangContactsRouteChildren: LangContactsRouteChildren = {
  LangContactsBookRoute: LangContactsBookRoute,
}

const LangContactsRouteWithChildren = LangContactsRoute._addFileChildren(
  LangContactsRouteChildren,
)

interface LangPricingRouteChildren {
  LangPricingBookRoute: typeof LangPricingBookRoute
}

const LangPricingRouteChildren: LangPricingRouteChildren = {
  LangPricingBookRoute: LangPricingBookRoute,
}

const LangPricingRouteWithChildren = LangPricingRoute._addFileChildren(
  LangPricingRouteChildren,
)

interface LangProductsRouteChildren {
  LangProductsBookRoute: typeof LangProductsBookRoute
}

const LangProductsRouteChildren: LangProductsRouteChildren = {
  LangProductsBookRoute: LangProductsBookRoute,
}

const LangProductsRouteWithChildren = LangProductsRoute._addFileChildren(
  LangProductsRouteChildren,
)

interface LangSpecialistsRouteChildren {
  LangSpecialistsBookRoute: typeof LangSpecialistsBookRoute
}

const LangSpecialistsRouteChildren: LangSpecialistsRouteChildren = {
  LangSpecialistsBookRoute: LangSpecialistsBookRoute,
}

const LangSpecialistsRouteWithChildren = LangSpecialistsRoute._addFileChildren(
  LangSpecialistsRouteChildren,
)

interface LangRouteChildren {
  LangSplatRoute: typeof LangSplatRoute
  LangBookRoute: typeof LangBookRoute
  LangContactsRoute: typeof LangContactsRouteWithChildren
  LangPricingRoute: typeof LangPricingRouteWithChildren
  LangProductsRoute: typeof LangProductsRouteWithChildren
  LangSpecialistsRoute: typeof LangSpecialistsRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangSplatRoute: LangSplatRoute,
  LangBookRoute: LangBookRoute,
  LangContactsRoute: LangContactsRouteWithChildren,
  LangPricingRoute: LangPricingRouteWithChildren,
  LangProductsRoute: LangProductsRouteWithChildren,
  LangSpecialistsRoute: LangSpecialistsRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface StudioLangContactsRouteChildren {
  StudioLangContactsBookRoute: typeof StudioLangContactsBookRoute
}

const StudioLangContactsRouteChildren: StudioLangContactsRouteChildren = {
  StudioLangContactsBookRoute: StudioLangContactsBookRoute,
}

const StudioLangContactsRouteWithChildren =
  StudioLangContactsRoute._addFileChildren(StudioLangContactsRouteChildren)

interface StudioLangPricingRouteChildren {
  StudioLangPricingBookRoute: typeof StudioLangPricingBookRoute
}

const StudioLangPricingRouteChildren: StudioLangPricingRouteChildren = {
  StudioLangPricingBookRoute: StudioLangPricingBookRoute,
}

const StudioLangPricingRouteWithChildren =
  StudioLangPricingRoute._addFileChildren(StudioLangPricingRouteChildren)

interface StudioLangProductsRouteChildren {
  StudioLangProductsBookRoute: typeof StudioLangProductsBookRoute
}

const StudioLangProductsRouteChildren: StudioLangProductsRouteChildren = {
  StudioLangProductsBookRoute: StudioLangProductsBookRoute,
}

const StudioLangProductsRouteWithChildren =
  StudioLangProductsRoute._addFileChildren(StudioLangProductsRouteChildren)

interface StudioLangSpecialistsRouteChildren {
  StudioLangSpecialistsBookRoute: typeof StudioLangSpecialistsBookRoute
}

const StudioLangSpecialistsRouteChildren: StudioLangSpecialistsRouteChildren = {
  StudioLangSpecialistsBookRoute: StudioLangSpecialistsBookRoute,
}

const StudioLangSpecialistsRouteWithChildren =
  StudioLangSpecialistsRoute._addFileChildren(
    StudioLangSpecialistsRouteChildren,
  )

interface StudioLangRouteChildren {
  StudioLangSplatRoute: typeof StudioLangSplatRoute
  StudioLangBookRoute: typeof StudioLangBookRoute
  StudioLangContactsRoute: typeof StudioLangContactsRouteWithChildren
  StudioLangPricingRoute: typeof StudioLangPricingRouteWithChildren
  StudioLangProductsRoute: typeof StudioLangProductsRouteWithChildren
  StudioLangSpecialistsRoute: typeof StudioLangSpecialistsRouteWithChildren
  StudioLangIndexRoute: typeof StudioLangIndexRoute
}

const StudioLangRouteChildren: StudioLangRouteChildren = {
  StudioLangSplatRoute: StudioLangSplatRoute,
  StudioLangBookRoute: StudioLangBookRoute,
  StudioLangContactsRoute: StudioLangContactsRouteWithChildren,
  StudioLangPricingRoute: StudioLangPricingRouteWithChildren,
  StudioLangProductsRoute: StudioLangProductsRouteWithChildren,
  StudioLangSpecialistsRoute: StudioLangSpecialistsRouteWithChildren,
  StudioLangIndexRoute: StudioLangIndexRoute,
}

const StudioLangRouteWithChildren = StudioLangRoute._addFileChildren(
  StudioLangRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LangRoute: LangRouteWithChildren,
  BuiucaniRoute: BuiucaniRoute,
  CenterRoute: CenterRoute,
  StudioLangRoute: StudioLangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
